[env:lilka]
board = lilka
build_src_filter = ${env.build_src_filter} +<../boards/lilka>
board_build.arduino.memory_type = qio_opi
board_build.partitions = custom_16Mb.csv
build_flags =
	${env.build_flags}
	-Iboards/lilka
	-Os
	-DCORE_DEBUG_LEVEL=1

	; Piezo buzzer (GPIO11 from schematic)
	-DBUZZ_PIN=11

	; Second SPI bus (modules on the extension header) -> HSPI peripheral
	-DUSE_HSPI_PORT=1

	-DDEVICE_NAME='"Lilka v2.3"'

lib_deps =
	${env.lib_deps}
